site_name: Python pour les Maths

theme:
  name: material
  logo: 'images/Python-logo.png'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
nav:
    - Home: index.md
    #- Nombres et calculs: fichier_notebook.ipynb
    #- Géométrie: exo.py
    #- Fonctions: page2.md
    #- Statistiques et probabilités: page3.md
    #- Algorithmique et programmation: page4.md

plugins:
  - mkdocs-jupyter
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lilabidi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EddyLabidi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/eddylabidi/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/lilabidi/mkdocs-learning"  target="_blank" rel="noopener">Eddy Labidi</a>